- name: Publish
  run: dotnet publish --configuration Release --output ./publish --runtime win-x86 --self-contained true

- name: Check publish folder        # ADD THIS
  run: |
    echo "Current directory:"
    pwd
    echo "Contents:"
    dir
    echo "Publish folder:"
    dir ./publish
  shell: pwsh

- name: Deploy to MonsterASP.NET via WebDeploy
  uses: rasmusbuchholdt/simply-web-deploy@2.1.0
  with:
    website-name: ${{ secrets.WEBSITE_NAME }}
    server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
    server-username: ${{ secrets.SERVER_USERNAME }}
    server-password: ${{ secrets.SERVER_PASSWORD }}
    source-path: './publish'
